pre-commit.d/check_mk_indentations: make robust
- split local a=b into local a and a=b so we can properly check success
- avoid 0 -ne 0 checks and inline commands into if ...; then
- break lines in error message
- set -o pipefail

diff --git a/.hooks/pre-commit.d/check_mk_indentations b/.hooks/pre-commit.d/check_mk_indentations
--- a/.hooks/pre-commit.d/check_mk_indentations
+++ b/.hooks/pre-commit.d/check_mk_indentations
@@ -9,28 +9,28 @@ if [ -r "${common_functions}" ]; then
 fi
 
 check_indentation() {
-	local mkfile="$1"
-	local name=$(printf %s "${mkfile}" | awk -F / '{print $NF}')
-	local tempdir=$(mktemp -d -t check_indentations-${name})
-	if [ $? -ne 0 ] ; then
-		echo "[pre-commit] failed to create tempdir"
+	local mkfile name tempdir
+	mkfile="$1"
+	name="${mkfile##*/}"
+	if ! tempdir="$(mktemp -d -t "check_indentations-${name}")" ; then
+		echo "[pre-commit] Failed to create tempdir"
 		exit 2
 	fi
-	cp "${mkfile}" "${tempdir}" && Tools/scripts/indent_make_if.pl "${tempdir}/${name}"
-	if [ $? -ne 0 ] ; then
-		pre_commit_error "failed to run Tools/scripts/indent_make_if.pl"
+	if ! cp "${mkfile}" "${tempdir}" || ! Tools/scripts/indent_make_if.pl "${tempdir}/${name}" ; then
+		pre_commit_error "Failed to run Tools/scripts/indent_make_if.pl"
 		exit 2
 	fi
-	cmp -s "${tempdir}"/*
-	if [ $? -ne 0 ] ; then
-		pre_commit_error "${mkfile} is not properly indented -- please use ${tempdir}/${name} which was created using Tools/scripts/indent_make_if.pl"
+	if ! cmp -s "${tempdir}"/* ; then
+		pre_commit_error "File '${mkfile}' is not properly indented"
+		error "                    Please use '${tempdir}/${name}',"
+	        error "                    which was created using Tools/scripts/indent_make_if.pl"
 		exit 1
 	fi
 }
 
 IFS=$'\n'
-modified_mks=$(git diff --name-only --cached --diff-filter=ACRM | grep -E '^Mk/.*\.mk$')
-if [ $? -eq 0 ] ; then
+set -o pipefail
+if modified_mks=$(git diff --name-only --cached --diff-filter=ACRM | grep -E '^Mk/.*\.mk$') ; then
 	for modified_mk in ${modified_mks} ; do
 		check_indentation "${modified_mk}"
 	done
