pre-commit: make logging clearer & configure git
Tweak messages.

Set git's core.quotePath temporarily via environment variable
so it thoroughly checks for unusal file names.

diff --git a/.hooks/pre-commit b/.hooks/pre-commit
--- a/.hooks/pre-commit
+++ b/.hooks/pre-commit
@@ -4,16 +4,23 @@
 # or exhaustively if PRE_COMMIT_KEEP_GOING is a nonempty environment variable
 #
 
-hook_directory=$(realpath $(dirname $0))
+hook_directory="$(realpath "$(dirname "$0")")"
+
+# enforce full filename checks
+export GIT_CONFIG_COUNT=1
+export GIT_CONFIG_KEY_0=core.quotePath
+export GIT_CONFIG_VALUE_0=true
 
 fail=0
-for hook in ${hook_directory}/pre-commit.d/* ; do
+for hook in "${hook_directory}"/pre-commit.d/* ; do
 	if [ -x "${hook}" ] ; then
-		${hook}
-		if [ $? -ne 0 ] ; then
-			if [ -z "$PRE_COMMIT_KEEP_GOING" ] ; then
-				echo >&2 "[pre-commit] INFO: Failing hook was ${hook}."
-				echo >&2 "[pre-commit] INFO: You can set PRE_COMMIT_KEEP_GOING=1 in the environment to see all errors."
+		if [ -n "${PRE_COMMIT_KEEP_GOING}" ] ; then
+			printf '[pre-commit] --- running %s\n' "${hook##*/}"
+		fi
+		if ! ${hook} ; then
+			echo >/dev/stderr "[pre-commit] REJECTED by ${hook}."
+			if [ -z "${PRE_COMMIT_KEEP_GOING}" ] ; then
+				echo >/dev/stderr "             You can set PRE_COMMIT_KEEP_GOING=1 in the environment to see all errors."
 				exit 1
 			else
 				fail=1
